const data1 = [
  {
    state: {
      name: 'Anambra',
      alias: 'anambra',
      lgas: [
        'Aguata',
        'Anambra East',
        'Anambra West',
        'Anaocha',
        'Awka North',
        'Awka South',
        'Ayamelum',
        'Dunukofia',
        'Ekwusigo',
        'Idemili North',
        'Idemili South',
        'Ihiala',
        'Njikoka',
        'Nnewi North',
        'Nnewi South',
        'Ogbaru',
        'Onitsha North',
        'Onitsha South',
        'Orumba North',
        'Orumba South',
        'Oyi',
      ],
    },
  },
  {
    state: {
      name: 'Abia',
      alias: 'abia',
      lgas: [
        'Aba North',
        'Aba South',
        'Arochukwu',
        'Bende',
        'Ikwuano',
        'Isiala Ngwa North',
        'Isiala Ngwa South',
        'Isuikwuato',
        'Obingwa',
        'Ohafia',
        'Osisioma',
        'Ugwunagbo',
        'Ukwa East',
        'Ukwa West',
        'Umuahia North',
        'Umuahia South',
        'Umu Nneochi',
      ],
    },
  },

  {
    state: {
       name: 'Akwa Ibom',
       alias: 'akwa_ibom',
       lgas: [
        'Abak',
        'Eastern Obolo',
        "Eket",
        "Esit Eket",
        "Essien Udim",
        "Etim Ekpo",
        "Etinan",
        "Ibeno",
        "Ibesikpo Asutan",
        "Ibiono-Ibom",
        "Ikot Abasi",
        "Ika",
        "Ikono",
        "Ikot Ekpene",
        "Ini",
        "Mkpat-Enin",
        "Itu",
        "Mbo",
        "Nsit-Atai",
        "Nsit-Ibom",
        "Nsit-Ubium",
        "Obot Akara",
        "Okobo",
        "Onna",
        "Oron",
        "Udung-Uko",
        "Ukanafun",
        "Oruk Anam",
        "Uruan",
        "Urue-Offong/Oruko",
        "Uyo",
      ],
    },
  },

  {
    state: {
      name: "Bayelsa",
      alias: "bayelsa",
      lgas: [
        "Brass",
        "Ekeremor",
        "Kolokuma/Opokuma",
        "Nembe",
        "Ogbia",
        "Sagbama",
        "Southern Ijaw",
        "Yenagoa"
      ],
    },
  },
  
  {
    state: {
      name: "Benue",
      alias: "benue",
      lgas: [
        "Agatu",
        "Apa",
        "Ado",
        "Buruku",
        "Gboko",
        "Guma",
        "Gwer East",
        "Gwer West",
        "Katsina-Ala",
        "Konshisha",
        "Kwande",
        "Logo",
        "Makurdi",
        "Obi",
        "Ogbadibo",
        "Ohimini",
        "Oju",
        "Okpokwu",
        "Oturkpo",
        "Tarka",
        "Ukum",
        "Ushongo",
        "Vandeikya"
      ],
    },
  },

  {
    state: {
      name: "Delta",
      alias: "delta",
      lgas: [
        "Aniocha North",
        "Aniocha South",
        "Bomadi",
        "Burutu",
        "Ethiope West",
        "Ethiope East",
        "Ika North East",
        "Ika South",
        "Isoko North",
        "Isoko South",
        "Ndokwa East",
        "Ndokwa West",
        "Okpe",
        "Oshimili North",
        "Oshimili South",
        "Patani",
        "Sapele",
        "Udu",
        "Ughelli North",
        "Ukwuani",
        "Ughelli South",
        "Uvwie",
        "Warri North",
        "Warri South",
        "Warri South West"
      ],
    },
  },
  
  {
    state: {
      name: 'Enugu',
      alias: 'enugu',
      lgas: [
        'Enugu East',
        'Enugu North',
        'Enugu South',
        'Ezeagu',
        'Igbo Etiti',
        'Igbo Eze North',
        'Igbo Eze South',
        'Isi Uzo',
        'Nkanu East',
        'Nkanu West',
        'Nsukka',
        'Oji River',
        'Udenu',
        'Udi',
        'Uzo-Uwani',
      ],
    },
  },
  {
    state: {
      name: 'Ebonyi',
      alias: 'ebonyi',
      lgas: [
        'Abakaliki',
        'Afikpo North',
        'Afikpo South',
        'Ebonyi',
        'Ezza North',
        'Ezza South',
        'Ikwo',
        'Ishielu',
        'Ivo',
        'Izzi',
        'Ohaozara',
        'Ohaukwu',
        'Onicha',
      ],
    },
  },
  {
    state: {
      name: 'Imo',
      alias: 'imo',
      lgas: [
        'Aboh-Mbaise',
        'Ahiazu-Mbaise',
        'Ehime-Mbano',
        'Ezinihitte',
        'Ideato North',
        'Ideato South',
        'Ihitte/Uboma',
        'Ikeduru',
        'Isiala Mbano',
        'Isu',
        'Mbaitoli',
        'Ngor-Okpala',
        'Njaba',
        'Nkwerre',
        'Nwangele',
        'Obowo',
        'Oguta',
        'Ohaji/Egbema',
        'Okigwe',
        'Orlu',
        'Orsu',
        'Oru East',
        'Oru West',
        'Owerri Municipal',
        'Owerri North',
        'Owerri West',
        'Unuimo',
      ],
    },
  },

  {
    state: {
      mame: "Kog",
      alias: "kogi",
      lgas: [
        "Ajaokuta",
        "Adavi",
        "Ankpa",
        "Bassa",
        "Dekina",
        "Ibaji",
        "Idah",
        "Igalamela Odolu",
        "Ijumu",
        "Kogi",
        "Kabba/Bunu",
        "Lokoja",
        "Ofu",
        "Mopa Muro",
        "Ogori/Magongo",
        "Okehi",
        "Okene",
        "Olamaboro",
        "Omala",
        "Yagba East",
        "Yagba West",
      ],
    },
  },

  {
    state: {
      name: "Rivers",
      alias: "rivers",
      lgas: [
        "Abua/Odual",
        "Ahoada East",
        "Ahoada West",
        "Andoni",
        "Akuku-Toru",
        "Asari-Toru",
        "Bonny",
        "Degema",
        "Emuoha",
        "Eleme",
        "Ikwerre",
        "Etche",
        "Gokana",
        "Khana",
        "Obio/Akpor",
        "Ogba/Egbema/Ndoni",
        "Ogu/Bolo",
        "Okrika",
        "Omuma",
        "Opobo/Nkoro",
        "Oyigbo",
        "Port Harcourt",
        "Tai",
      ],
    },
  },
];


export default data1
